services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterRssWidgets\:
    resource: '../Classes/*'

  dashboard.views.brotkrueml.jobrouter_rss_widgets.widget:
    class: 'TYPO3\CMS\Fluid\View\StandaloneView'
    public: true
    factory: ['Brotkrueml\JobRouterRssWidgets\Dashboard\Views\Factory', 'widgetTemplate']

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.blog_en:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_en.more'
      $link: 'https://www.jobrouter.com/en/blog/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.blog_de:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_de.more'
      $link: 'https://www.jobrouter.com/de/blog/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.downloads_en:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_en.more'
      $link: 'https://www.jobrouter.com/en/downloads/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.downloads_de:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_de.more'
      $link: 'https://www.jobrouter.com/de/downloads/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.press_en:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_en.more'
      $link: 'https://www.jobrouter.com/en/press/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.press_de:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_de.more'
      $link: 'https://www.jobrouter.com/de/presse/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.videos_en:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_en.more'
      $link: 'https://www.jobrouter.com/en/videos/'
      $target: '_blank'

  dashboard.buttons.brotkrueml.jobrouter_rss_widgets.videos_de:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_de.more'
      $link: 'https://www.jobrouter.com/de/videos/'
      $target: '_blank'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.blog_en:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\PictureRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.blog_en'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/en/blog/blog.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_blog_en'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_en.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_en.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.blog_de:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\PictureRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.blog_de'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/de/blog/blog.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_blog_de'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_de.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.blog_de.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.downloads_en:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\PictureRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.downloads_en'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/en/downloads/downloads.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_downloads_en'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_en.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_en.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.downloads_de:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\PictureRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.downloads_de'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/de/downloads/downloads.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_downloads_de'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_de.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.downloads_de.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.press_en:
    class: 'TYPO3\CMS\Dashboard\Widgets\RssWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $cache: '@cache.dashboard.rss'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.press_en'
      $options:
        feedUrl: 'https://www.jobrouter.com/en/press/press.rss'
        lifeTime: 43200
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_press_en'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_en.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_en.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.press_de:
    class: 'TYPO3\CMS\Dashboard\Widgets\RssWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $cache: '@cache.dashboard.rss'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.press_de'
      $options:
        feedUrl: 'https://www.jobrouter.com/de/presse/press.rss'
        lifeTime: 43200
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_press_de'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_de.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.press_de.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.videos_en:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\VideoRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.videos_en'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/en/videos/video.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_videos_en'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_en.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_en.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'

  dashboard.widget.brotkrueml.jobrouter_rss_widgets.videos_de:
    class: 'Brotkrueml\JobRouterRssWidgets\Dashboard\Widgets\VideoRssWidget'
    arguments:
      $view: '@dashboard.views.brotkrueml.jobrouter_rss_widgets.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.jobrouter_rss_widgets.videos_de'
      $cache: '@cache.dashboard.rss'
      $options:
        feedUrl: 'https://www.jobrouter.com/de/videos/video.rss'
    tags:
      - name: dashboard.widget
        identifier: 'jobrouter_rss_widgets_videos_de'
        groupNames: 'jobrouter'
        title: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_de.title'
        description: 'LLL:EXT:jobrouter_rss_widgets/Resources/Private/Language/Dashboard.xlf:widgets.videos_de.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'
