name: CI

on:
  push:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'

jobs:
  build:
    name: Build PHP/TYPO3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        typo3-versions: ['^10', '^11']
        include:
          - php-versions: 7.2
            typo3-versions: ^10
          - php-versions: 7.3
            typo3-versions: ^10
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: fileinfo gd intl json mbstring mysqli openssl pcre pdo session xml zip zlib
      - name: Install composer dependencies
        run: |
          composer self-update
          composer --version
          composer require typo3/cms-core=${{ matrix.typo3-versions }} --no-progress
          git checkout composer.json
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./.Build/*" -exec php -l {} \;
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring
      - name: Install composer dependencies
        run: |
          composer --version
          composer install
      - name: Check coding standards
        run: |
          .Build/bin/ecs check --no-progress-bar
      - name: Run unit tests
        run: |
          .Build/bin/phpunit -c Tests/phpunit.xml.dist --log-junit .Build/logs/phpunit.xml --coverage-text --coverage-clover .Build/logs/clover.xml
      - name: Run psalm
        run: |
          .Build/bin/psalm --no-progress --monochrome
  xliff-validation:
    name: XLIFF validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install package
        run: |
          sudo apt-get -y install libxml2-utils
      - name: Download XSD
        run: |
          curl --no-progress-meter -O https://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core-1.2-strict.xsd
      - name: Validate XLIFF files
        run: |
          xmllint --schema xliff-core-1.2-strict.xsd --noout Resources/Private/Language/*.xlf
