name: CI

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'

jobs:
  build:
    name: Build PHP/TYPO3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        typo3-versions: ['^10']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: fileinfo gd intl json mbstring mysqli openssl pcre pdo session xml zip zlib
      - name: Install composer dependencies
        run: |
          composer self-update
          composer --version
          composer require typo3/cms-core=${{ matrix.typo3-versions }} --no-progress
          git checkout composer.json
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./.Build/*" -exec php -l {} \;
      - name: Run psalm
        run: |
          .Build/bin/psalm --no-progress --monochrome
